name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            container: 
              image: debian:11
              volumes:
                - /home/runner/work:/home/runner/work


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6

      - name: Run test
        uses: ./
        with:
          plugins-path: ./plugins

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./plugins