name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [buntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6

      - name: Run test
        uses: ./
        with:
          plugins-path: ./plugins

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./plugins